name: credit-risk-scoring
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - xgboost
  - shap
  - plotly
  - seaborn
  - pip:
    - python-dotenv
    - -e .

